[package]
name = "ray_tracing"
version = "0.1.0"
edition = "2024"

[dependencies]
glam = { version = "0.30.9", features = ["rand"] }
indicatif = { version = "0.18.3", features = ["rayon"] }
rand = { version = "0.9.2", features = ["small_rng"] }
rayon = "1.11.0"
